galaxy_info:
  author: Eugene Ignatov
  description: Create and configure a systemd service
  role_name: systemd_service
  company: Cimon.io
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
    - name: Ubuntu
      versions:
      - xenial
      - yakkety
      - zesty
      - artful
      - bionic
      - cosmic
      - disco
    - name: Debian
      versions:
      - jessie
      - stretch
      - buster
      - bullseye
    - name: EL
      versions:
      - 7
      - 8

  galaxy_tags:
    - service
    - system
    - systemd

dependencies: []
